# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4adbadb01d1d06a3b7d9d2708f0908f24ea22e70be33eb0315c2c5759c134e63d803ea13759c314436837c6e9809c92c18d87f22946e306570975cc0418b074

test:
  secret_key_base: e4633f4a8d0c1671d31927182fe74133bc2913fcf039cebc8d54dfa7f5a1e7d7298fcf8984d953bfaaec421674f9cb71bbfac7d168066918d5c0e3bd7b7b8e98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
